from __future__ import annotations

from collections import Counter
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
import re
import statistics
from pathlib import Path
from typing import Any, Dict, Iterable, Optional

from ..gitops import git_stdout
from ..sdlc import clamp01

_GENERIC_MESSAGE_RE = re.compile(
    r"^(update|fix|refactor|cleanup|changes|misc|wip|minor|tweak|improve|adjust|sync|bump)(\b|:)",
    re.IGNORECASE,
)
_BOT_RE = re.compile(r"(\[bot\]|bot$|bot@|github-actions|dependabot|renovate)", re.IGNORECASE)
_AI_KEYWORD_RE = re.compile(
    r"(copilot|chatgpt|gpt[- ]?4|claude|cursor|aider|llm|ollama|anthropic|gemini|ai agent|agentic|generated by ai|ai-assisted)",
    re.IGNORECASE,
)
_AI_ATTRIBUTION_RE = re.compile(
    r"(generated by ai|written with ai|ai-assisted|co-authored-by:.*(gpt|claude|copilot|cursor|aider)|copilot|chatgpt|claude|cursor|aider|gemini)",
    re.IGNORECASE,
)
_DOC_PATH_RE = re.compile(r"(^|/)(readme|docs?|architecture|adr|design|spec|specs|guide|guides|manual)(/|\.|$)", re.IGNORECASE)


@dataclass(frozen=True)
class AIInfluenceDetails:
    ai_influence_score: float
    ai_influence_confidence: float
    weighted_base_score: float
    temporal_adoption_prior: float
    temporal_anomaly_weight: float
    dominant_activity_period: str | None
    historical_constraint_applied: bool
    legacy_variance_protection_applied: bool
    ai_influence_rationale: list[str]
    ai_h1_textual_markers: float | None
    ai_h2_explicit_attribution: float | None
    ai_h3_temporal_prior: float
    ai_h4_burstiness: float | None
    ai_h5_style_shift: float | None
    ai_h6_large_low_discussion: float | None
    ai_h7_output_asymmetry: float | None
    ai_h8_tooling_footprint: float | None
    ai_h9_generated_text_pattern: float | None
    commit_pattern_score: float | None
    temporal_anomaly_score: float | None
    temporal_anomaly_score_raw: float | None
    style_uniformity_score: float | None
    metadata_signal_score: float | None

    def as_dict(self) -> Dict[str, Any]:
        return asdict(self)


def _safe_mean(values: Iterable[float | None]) -> float | None:
    filtered = [float(v) for v in values if v is not None]
    if not filtered:
        return None
    return sum(filtered) / len(filtered)


def _count_hits(items: Iterable[str], pattern: re.Pattern[str]) -> int:
    return sum(1 for item in items if pattern.search(item))


def _normalize_weighted_score(subscores: Dict[str, float | None], weights: Dict[str, float]) -> float:
    available = {key: value for key, value in subscores.items() if value is not None and key in weights}
    if not available:
        return 0.0

    total_weight = sum(weights[key] for key in available)
    if total_weight <= 0:
        return 0.0

    return sum((weights[key] / total_weight) * float(value) for key, value in available.items())


def _parse_commit_log(repo_dir: Path, ref: str = "HEAD") -> list[dict[str, Any]]:
    out = git_stdout(
        repo_dir,
        ["log", "--format=__BIGUA_COMMIT__%n%s%n%ct%n%aN <%aE>", "--numstat", ref],
    ).strip()
    if not out:
        return []

    commits: list[dict[str, Any]] = []
    current: dict[str, Any] | None = None
    header_line_index = 0

    for raw_line in out.splitlines():
        line = raw_line.rstrip("\n")
        if line == "__BIGUA_COMMIT__":
            if current is not None:
                commits.append(current)
            current = {
                "message": "",
                "timestamp": None,
                "author": "",
                "files_changed": 0,
                "lines_changed": 0,
            }
            header_line_index = 0
            continue

        if current is None:
            continue

        if header_line_index == 0:
            current["message"] = line.strip()
            header_line_index = 1
            continue
        if header_line_index == 1:
            try:
                current["timestamp"] = int(line.strip())
            except ValueError:
                current["timestamp"] = None
            header_line_index = 2
            continue
        if header_line_index == 2:
            current["author"] = line.strip()
            header_line_index = 3
            continue

        if not line.strip():
            continue

        parts = line.split("\t")
        if len(parts) != 3:
            continue

        inserted_raw, deleted_raw, _path = parts
        inserted = 0 if inserted_raw == "-" else int(inserted_raw)
        deleted = 0 if deleted_raw == "-" else int(deleted_raw)
        current["files_changed"] += 1
        current["lines_changed"] += inserted + deleted

    if current is not None:
        commits.append(current)

    return commits


def collect_repository_ai_data(repo_dir: Path, ref: str = "HEAD") -> Dict[str, Any]:
    commits = _parse_commit_log(repo_dir, ref)
    tree_output = git_stdout(repo_dir, ["ls-tree", "-r", "--name-only", ref]).strip()
    file_paths = [line.strip() for line in tree_output.splitlines() if line.strip()]

    return {
        "commits": commits,
        "file_paths": file_paths,
    }


def _generic_message_ratio(commits: list[dict[str, Any]]) -> float | None:
    if not commits:
        return None
    generic = 0
    for commit in commits:
        message = str(commit.get("message", "")).strip()
        if not message:
            continue
        if len(message.split()) <= 2 or _GENERIC_MESSAGE_RE.search(message):
            generic += 1
    return generic / len(commits)


def _large_commit_ratio(commits: list[dict[str, Any]]) -> float | None:
    if not commits:
        return None
    large = sum(
        1
        for commit in commits
        if (commit.get("lines_changed") or 0) >= 200 or (commit.get("files_changed") or 0) >= 12
    )
    return large / len(commits)


def _low_granularity_ratio(commits: list[dict[str, Any]]) -> float | None:
    if not commits:
        return None
    coarse = sum(1 for commit in commits if (commit.get("files_changed") or 0) >= 8)
    return coarse / len(commits)


def _generated_text_pattern_score(commits: list[dict[str, Any]]) -> float | None:
    if not commits:
        return None

    normalized_messages = []
    for commit in commits:
        message = str(commit.get("message", "")).strip().lower()
        if not message:
            continue
        normalized_messages.append(re.sub(r"\d+", "#", message))

    if not normalized_messages:
        return None

    repeated_ratio = sum(count - 1 for count in Counter(normalized_messages).values() if count > 1) / len(normalized_messages)
    return _safe_mean([repeated_ratio, _generic_message_ratio(commits)])


def _large_low_discussion_score(commits: list[dict[str, Any]]) -> float | None:
    return _safe_mean([_large_commit_ratio(commits), _generic_message_ratio(commits)])


def _output_asymmetry_score(commits: list[dict[str, Any]]) -> float | None:
    return _safe_mean([_large_commit_ratio(commits), _low_granularity_ratio(commits)])


def compute_commit_pattern_score(repo_data: Dict[str, Any]) -> float | None:
    commits = list(repo_data.get("commits", []))
    return _safe_mean(
        [
            _large_commit_ratio(commits),
            _generic_message_ratio(commits),
            _low_granularity_ratio(commits),
            _generated_text_pattern_score(commits),
        ]
    )


def compute_temporal_anomaly_score(repo_data: Dict[str, Any]) -> float | None:
    commits = list(repo_data.get("commits", []))
    timestamps = [int(commit["timestamp"]) for commit in commits if commit.get("timestamp") is not None]
    if not timestamps:
        return None

    day_counts = Counter(ts // 86400 for ts in timestamps)
    hour_counts = Counter(ts // 3600 for ts in timestamps)

    daily_values = list(day_counts.values())
    hourly_values = list(hour_counts.values())

    if not daily_values:
        return None

    if len(daily_values) == 1:
        burst_ratio = 1.0 if daily_values[0] >= 8 else 0.0
    else:
        mean_daily = statistics.mean(daily_values)
        stdev_daily = statistics.stdev(daily_values)
        burst_threshold = max(5.0, mean_daily + stdev_daily)
        burst_ratio = sum(1 for count in daily_values if count >= burst_threshold) / len(daily_values)

    peak_day_score = clamp01(max(daily_values) / 20.0)
    peak_hour_score = clamp01(max(hourly_values) / 6.0) if hourly_values else 0.0
    return _safe_mean([burst_ratio, peak_day_score, peak_hour_score])


def _temporal_anomaly_weight(repo_data: Dict[str, Any]) -> float:
    repo_age_days = repo_data.get("repo_age_days")
    if repo_age_days is None:
        return 1.0
    try:
        age = max(0.0, float(repo_age_days))
    except (TypeError, ValueError):
        return 1.0
    return clamp01(age / 90.0)


def compute_style_uniformity_score(repo_data: Dict[str, Any]) -> float | None:
    file_paths = list(repo_data.get("file_paths", []))
    if not file_paths:
        return None

    extensions = [Path(path).suffix.lower() or "<none>" for path in file_paths]
    extension_counts = Counter(extensions)
    extension_dominance = max(extension_counts.values()) / len(file_paths)

    basenames = [Path(path).name.lower() for path in file_paths]
    basename_counts = Counter(basenames)
    repeated_basenames = sum(count - 1 for count in basename_counts.values() if count > 1)
    basename_repetition_ratio = repeated_basenames / len(file_paths)

    depths = [path.count("/") + path.count("\\") for path in file_paths]
    if len(depths) < 2:
        depth_uniformity = 1.0
    else:
        depth_stdev = statistics.stdev(depths)
        depth_uniformity = 1.0 - clamp01(depth_stdev / 4.0)

    score = _safe_mean([extension_dominance, basename_repetition_ratio, depth_uniformity])
    if score is None:
        return None

    commit_count = len(list(repo_data.get("commits", [])))
    if commit_count < 50:
        score *= 0.6

    return clamp01(score)


def _bot_commit_ratio(commits: list[dict[str, Any]]) -> float | None:
    if not commits:
        return None
    bot_commits = 0
    for commit in commits:
        author = str(commit.get("author", ""))
        message = str(commit.get("message", ""))
        if _BOT_RE.search(author) or _BOT_RE.search(message):
            bot_commits += 1
    return bot_commits / len(commits)


def _ai_reference_score(commits: list[dict[str, Any]], file_paths: list[str]) -> float | None:
    corpus = []
    corpus.extend(str(commit.get("message", "")) for commit in commits)
    corpus.extend(file_paths)
    if not corpus:
        return None
    hits = sum(1 for item in corpus if _AI_KEYWORD_RE.search(item))
    return clamp01(hits / max(5, len(corpus)))


def _explicit_ai_attribution_score(commits: list[dict[str, Any]], file_paths: list[str]) -> float | None:
    corpus = []
    corpus.extend(str(commit.get("message", "")) for commit in commits)
    corpus.extend(file_paths)
    if not corpus:
        return None
    hits = _count_hits(corpus, _AI_ATTRIBUTION_RE)
    return clamp01(hits / max(3, len(corpus)))


def _automation_artifact_score(file_paths: list[str]) -> float | None:
    if not file_paths:
        return None

    indicators = [
        any(path.startswith(".github/workflows/") for path in file_paths),
        any(path.startswith("scripts/") for path in file_paths),
        any("agent" in path.lower() or "copilot" in path.lower() for path in file_paths),
    ]
    return sum(1.0 for present in indicators if present) / len(indicators)


def _documentation_signal_score(file_paths: list[str]) -> float:
    if not file_paths:
        return 0.0
    doc_hits = _count_hits(file_paths, _DOC_PATH_RE)
    return clamp01(doc_hits / max(5, len(file_paths)))


def compute_metadata_signal_score(repo_data: Dict[str, Any]) -> float | None:
    commits = list(repo_data.get("commits", []))
    file_paths = list(repo_data.get("file_paths", []))
    components = [
        _bot_commit_ratio(commits),
        _ai_reference_score(commits, file_paths),
        _explicit_ai_attribution_score(commits, file_paths),
        _automation_artifact_score(file_paths),
    ]
    score = _safe_mean(components)
    if score is None:
        return None

    commit_count = len(commits)
    positive_components = sum(1 for value in components if value is not None and value >= 0.2)
    sparsity_factor = 1.0
    if commit_count < 50:
        sparsity_factor *= 0.8
    if positive_components <= 1:
        sparsity_factor *= 0.75

    return clamp01(score * sparsity_factor)


def _dominant_activity_period(repo_data: Dict[str, Any]) -> str | None:
    commits = list(repo_data.get("commits", []))
    timestamps = [int(commit["timestamp"]) for commit in commits if commit.get("timestamp") is not None]
    if not timestamps:
        return None

    buckets = Counter()
    for ts in timestamps:
        year = int(git_time_year(ts))
        if year < 2022:
            buckets["before-2022"] += 1
        elif year < 2024:
            buckets["2022-2023"] += 1
        else:
            buckets["2024+"] += 1

    if not buckets:
        return None
    return buckets.most_common(1)[0][0]


def git_time_year(timestamp: int) -> int:
    return datetime.fromtimestamp(timestamp, tz=timezone.utc).year


def _temporal_adoption_prior(period: str | None) -> float:
    if period == "2022-2023":
        return 0.05
    if period == "2024+":
        return 0.10
    return 0.0


def _project_age_years(repo_data: Dict[str, Any]) -> float:
    repo_age_days = repo_data.get("repo_age_days")
    if repo_age_days is None:
        return 0.0
    try:
        return max(0.0, float(repo_age_days) / 365.25)
    except (TypeError, ValueError):
        return 0.0


def _dominant_activity_year(repo_data: Dict[str, Any]) -> int | None:
    commits = list(repo_data.get("commits", []))
    timestamps = [int(commit["timestamp"]) for commit in commits if commit.get("timestamp") is not None]
    if not timestamps:
        return None

    years = Counter(git_time_year(ts) for ts in timestamps)
    if not years:
        return None
    return int(years.most_common(1)[0][0])


def _is_modern_context(repo_data: Dict[str, Any], dominant_period: str | None) -> bool:
    if dominant_period == "2024+":
        return True
    if dominant_period != "2022-2023":
        return False
    dominant_year = _dominant_activity_year(repo_data)
    return dominant_year is not None and dominant_year >= 2023


def _has_boost_support(
    subscores: Dict[str, float | None],
    h6_large_low_discussion: float | None,
    h7_output_asymmetry: float | None,
    h9_generated_text_pattern: float | None,
) -> bool:
    non_temporal = [
        subscores.get("commit_pattern_score"),
        subscores.get("style_uniformity_score"),
        subscores.get("metadata_signal_score"),
        h6_large_low_discussion,
        h7_output_asymmetry,
        h9_generated_text_pattern,
    ]
    present = [float(value) for value in non_temporal if value is not None]
    moderate = sum(1 for value in present if value >= 0.2)
    weak = sum(1 for value in present if value >= 0.12)
    return moderate >= 2 or (moderate >= 1 and weak >= 3)


def _infer_contributor_count(repo_data: Dict[str, Any], commits: list[dict[str, Any]]) -> int:
    raw = repo_data.get("contributor_count")
    if raw is not None:
        try:
            return max(0, int(raw))
        except (TypeError, ValueError):
            pass

    authors = {str(commit.get("author", "")).strip() for commit in commits if str(commit.get("author", "")).strip()}
    return len(authors)


def _compute_confidence(repo_data: Dict[str, Any]) -> float:
    commits = list(repo_data.get("commits", []))
    file_paths = list(repo_data.get("file_paths", []))
    docs_signal = _documentation_signal_score(file_paths)
    commit_count = len(commits)
    file_count = len(file_paths)

    availability_score = (
        0.35 * (1.0 if commits else 0.0)
        + 0.10 * (1.0 if repo_data.get("pull_requests") else 0.0)
        + 0.10 * (1.0 if repo_data.get("issues") else 0.0)
        + 0.30 * (1.0 if file_paths else 0.0)
        + 0.15 * docs_signal
    )
    density_score = _safe_mean(
        [
            clamp01(commit_count / 200.0),
            clamp01(file_count / 100.0),
            docs_signal,
        ]
    ) or 0.0
    confidence = availability_score * (0.55 + 0.45 * density_score)
    return clamp01(confidence)


def _top_rationale_signals(signal_map: Dict[str, float | None], limit: int = 3) -> list[str]:
    ranked = sorted(
        ((label, float(value)) for label, value in signal_map.items() if value is not None and value > 0.15),
        key=lambda item: item[1],
        reverse=True,
    )
    return [label for label, _ in ranked[:limit]]


def _has_strong_signal_diversity(subscores: Dict[str, float | None]) -> bool:
    valid = [float(value) for value in subscores.values() if value is not None]
    moderate_count = sum(1 for value in valid if value >= 0.45)
    strong_count = sum(1 for value in valid if value >= 0.70)
    weak_count = sum(1 for value in valid if value >= 0.20)
    return moderate_count >= 2 or (strong_count >= 1 and weak_count >= 3)


def compute_ai_influence_details(repo_data: Dict[str, Any]) -> AIInfluenceDetails:
    commits = list(repo_data.get("commits", []))
    file_paths = list(repo_data.get("file_paths", []))
    commit_count = len(commits)
    contributor_count = _infer_contributor_count(repo_data, commits)

    temporal_raw = compute_temporal_anomaly_score(repo_data)
    temporal_weight = _temporal_anomaly_weight(repo_data)
    temporal_adjusted = None if temporal_raw is None else clamp01(temporal_raw * temporal_weight)

    h1_textual_markers = _ai_reference_score(commits, file_paths)
    h2_explicit_attribution = _explicit_ai_attribution_score(commits, file_paths)
    h6_large_low_discussion = _large_low_discussion_score(commits)
    h7_output_asymmetry = _output_asymmetry_score(commits)
    h8_tooling_footprint = _automation_artifact_score(file_paths)
    h9_generated_text_pattern = _generated_text_pattern_score(commits)

    subscores = {
        "commit_pattern_score": compute_commit_pattern_score(repo_data),
        "temporal_anomaly_score": temporal_adjusted,
        "style_uniformity_score": compute_style_uniformity_score(repo_data),
        "metadata_signal_score": compute_metadata_signal_score(repo_data),
    }
    weights = {
        "commit_pattern_score": 0.30,
        "temporal_anomaly_score": 0.20,
        "style_uniformity_score": 0.30,
        "metadata_signal_score": 0.20,
    }
    weighted_base_score = _normalize_weighted_score(subscores, weights)
    dominant_period = _dominant_activity_period(repo_data)
    temporal_prior = _temporal_adoption_prior(dominant_period)
    ai_score = clamp01(weighted_base_score + temporal_prior)

    historical_feasibility_factor = 1.0
    historical_constraint_applied = False
    if dominant_period == "before-2022":
        historical_feasibility_factor = 0.4
        historical_constraint_applied = True
        ai_score *= historical_feasibility_factor
        max_non_temporal = max(
            [float(value) for value in [subscores["commit_pattern_score"], subscores["style_uniformity_score"], subscores["metadata_signal_score"]] if value is not None],
            default=0.0,
        )
        if max_non_temporal < 0.55:
            ai_score = min(ai_score, 0.29)
        else:
            ai_score = min(ai_score, 0.59)

    legacy_variance_factor = 1.0
    legacy_variance_protection_applied = False
    if _project_age_years(repo_data) > 10.0 and commit_count >= 1000:
        legacy_variance_factor = 0.7
        legacy_variance_protection_applied = True
        ai_score *= legacy_variance_factor

    if ai_score >= 0.70 and not _has_strong_signal_diversity(subscores):
        ai_score = 0.69

    confidence = _compute_confidence(repo_data)
    rationale_boosts: list[str] = []

    ai_score_before_v13_boosts = clamp01(ai_score)
    if not historical_constraint_applied:
        boost_supported = _has_boost_support(
            subscores,
            h6_large_low_discussion,
            h7_output_asymmetry,
            h9_generated_text_pattern,
        )
        if _is_modern_context(repo_data, dominant_period) and boost_supported:
            ai_score *= 1.15
            rationale_boosts.append("modern development context")

        output_asymmetry_boost = 0.0
        if commit_count >= 20 and contributor_count <= 2 and boost_supported:
            asymmetry_factor = min(0.1, commit_count / 500.0)
            output_asymmetry_boost = asymmetry_factor * 0.5
            ai_score += output_asymmetry_boost
            if output_asymmetry_boost > 0:
                rationale_boosts.append("high output asymmetry")

        low_discussion_boost = 0.0
        if h6_large_low_discussion is not None and h6_large_low_discussion > 0.3 and boost_supported:
            low_discussion_boost = 0.07
            ai_score += low_discussion_boost
            rationale_boosts.append("low discussion relative to output")

        total_boost = ai_score - ai_score_before_v13_boosts
        if total_boost > 0.15:
            ai_score = ai_score_before_v13_boosts + 0.15
            rationale_boosts.append("controlled boost cap")

        if ai_score_before_v13_boosts < 0.60 and ai_score >= 0.70:
            ai_score = 0.69
            rationale_boosts.append("controlled boost boundary")

    if confidence < 0.4:
        ai_score *= 0.9
        rationale_boosts.append("low-confidence evidence adjustment")
        if ai_score >= 0.70:
            ai_score = 0.69
            rationale_boosts.append("low-confidence boundary")

    if ai_score >= 0.70 and not _has_strong_signal_diversity(subscores):
        ai_score = 0.69

    ai_score = clamp01(ai_score)

    rationale = _top_rationale_signals(
        {
            "temporal concentration": subscores["temporal_anomaly_score"],
            "moderate style uniformity": subscores["style_uniformity_score"],
            "metadata/tooling signals": subscores["metadata_signal_score"],
            "commit pattern cues": subscores["commit_pattern_score"],
            "textual AI markers": h1_textual_markers,
            "explicit AI attribution": h2_explicit_attribution,
            "generated text patterns": h9_generated_text_pattern,
        }
    )
    if dominant_period == "before-2022":
        rationale.append("historical feasibility constraint")
    if legacy_variance_factor < 1.0:
        rationale.append("legacy variance protection")
    if confidence < 0.45:
        rationale.append("limited repository evidence coverage")
    for boost_reason in rationale_boosts:
        if boost_reason not in rationale:
            rationale.append(boost_reason)
    if not rationale:
        rationale = ["insufficient repository evidence"]

    return AIInfluenceDetails(
        ai_influence_score=ai_score,
        ai_influence_confidence=confidence,
        weighted_base_score=weighted_base_score,
        temporal_adoption_prior=temporal_prior,
        temporal_anomaly_weight=temporal_weight,
        dominant_activity_period=dominant_period,
        historical_constraint_applied=historical_constraint_applied,
        legacy_variance_protection_applied=legacy_variance_protection_applied,
        ai_influence_rationale=rationale,
        ai_h1_textual_markers=h1_textual_markers,
        ai_h2_explicit_attribution=h2_explicit_attribution,
        ai_h3_temporal_prior=temporal_prior,
        ai_h4_burstiness=temporal_adjusted,
        ai_h5_style_shift=subscores["style_uniformity_score"],
        ai_h6_large_low_discussion=h6_large_low_discussion,
        ai_h7_output_asymmetry=h7_output_asymmetry,
        ai_h8_tooling_footprint=h8_tooling_footprint,
        ai_h9_generated_text_pattern=h9_generated_text_pattern,
        commit_pattern_score=subscores["commit_pattern_score"],
        temporal_anomaly_score=subscores["temporal_anomaly_score"],
        temporal_anomaly_score_raw=temporal_raw,
        style_uniformity_score=subscores["style_uniformity_score"],
        metadata_signal_score=subscores["metadata_signal_score"],
    )


def compute_ai_influence(repo_data: Dict[str, Any]) -> float:
    """
    Return a score between 0 and 1 indicating likelihood of AI-assisted development
    at the repository level.
    """
    return compute_ai_influence_details(repo_data).ai_influence_score